language: ruby
sudo: false
rvm:
  - 2.1.0

branches:
  except:
    - old-master
    - release/betty/master
    - release/elefante/master
    - release/essex-hack/master
    - release/fledermaus/master
    - release/fred/master
    - release/hydrogen/master
    - release/pebbles/master
    - release/roxy/master
    - /^release\/.*\/master-bootstrap-ui$/
    - /^release\/hadoop-.*$/
    - /^release\/mesa-.*$/
    - /^release\/suse-cloud\/.*$/

gemfile: crowbar_framework/Gemfile

install:
  - cd crowbar_framework
  - bundle install
  - bundle exec rake db:create db:migrate

script:
  - bundle exec rake spec
  - bundle exec rake brakeman:run
  - bundle exec bundle-audit update
    # ignore rest-client issues, chef 10 requires that
  - bundle exec bundle-audit check --ignore CVE-2015-1820 OSVDB-117461
