language: ruby
rvm:
  - 2.1.0

gemfile: crowbar_framework/Gemfile

before_install:
  - gem update --system 1.8.23
  - gem --version

install:
  - cd crowbar_framework
  - bundle install
  - bundle exec rake db:create db:migrate

script:
  - bundle exec rake spec
  - bundle exec rake brakeman:run
