language: ruby
rvm:
  - "1.8.7"
branches:
  only:
    - release/stoney/master
gemfile: crowbar_framework/Gemfile
before_install:
  - gem update --system 1.8.23
  - gem --version
install:
  - cd crowbar_framework
  - bundle install --without development
  - bundle exec rake db:migrate
  - sed -i -e "s#use_bundler\:\ false#use_bundler\:\ true#" config/app_config.yml
  - cp config/catalog.yml.example config/catalog.yml
script:
  - bundle exec rake spec
